### ISSUE TITLE
Docker MySQL container does not build

### ISSUE THREAD

**Issue by fbartels** [dstar4138/standardfile#6]
Hi, I've stumbled over your project since I wanted to give standardfile (for standardnotes) a try. Unfortunately running `docker-compose build` runs into an error since the file added in https://github.com/dstar4138/standardfile/blob/cbb81ad2e191840cab6a6c1cbc54619984d33baf/docker/Dockerfile-db#L4 does not exist in this repo.

**Comment by dstar4138** [comment]
Thank you for the issue report!

Looks like I messed up the `.gitignore`, I'll get a fix out asap!

**Comment by dstar4138** [comment]
Ok, this commit (on the `develop` branch) should fix the issues for you: https://github.com/dstar4138/standardfile/commit/9081d54a80e9fcb1ba05ef310cb9b186a81afffa

oh, and for what it's worth, this server still uses the older 002 protocol. You can see the difference with 003 here:
https://github.com/standardfile/forum/issues/3

I haven't had the time to invest in reworking the auth stuff yet, so please forgive me. I have been using client 2.1.32, with my personal docker instance. But i just updated to 3.0.6 and it looks like it works regardless.

I'll go ahead and close this issue, but please let me know if this didn't work

**Comment by fbartels** [comment]
Hi, thanks for looking into this. I just now got to testing your changes out and the database now build, but I think I see another issue with this. I'll have another stab at building the container and will open a new issue if I see the error again.
